/**
 * Created by TP on 2017/7/27.
 */
import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const systems = [
      {id: 0, sysname: 'dev', creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', role: '开发', email: 'dev@enmotech.com',
        dbname: 'ddltest', host: 'oel6idb', function: '开发'},
      {id: 1, sysname: 'dba', creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', role: '开发', email: 'dev@enmotech.com',
        dbname: 'ddltest', host: 'oel6idb', function: '开发'},
      {id: 2, sysname: 'abc', creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', role: '开发', email: 'dev@enmotech.com',
        dbname: 'ddltest', host: 'oel6idb', function: '开发'},
      {id: 3, sysname: 'eee', creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', role: '开发', email: 'dev@enmotech.com',
        dbname: 'ddltest', host: 'oel6idb', function: '开发'},
      {id: 4, sysname: 'dev', creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', role: '开发', email: 'dev@enmotech.com',
        dbname: 'ddltest', host: 'oel6idb', function: '开发'},
      {id: 5, sysname: 'dev', creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', role: '开发', email: 'dev@enmotech.com',
        dbname: 'ddltest', host: 'oel6idb', function: '开发'},
      {id: 6, sysname: 'dev', creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', role: '开发', email: 'dev@enmotech.com',
        dbname: 'ddltest', host: 'oel6idb', function: '开发'},
      {id: 7, sysname: 'dev', creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', role: '开发', email: 'dev@enmotech.com',
        dbname: 'ddltest', host: 'oel6idb', function: '开发'},
      {id: 8, sysname: 'dev', creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', role: '开发', email: 'dev@enmotech.com',
        dbname: 'ddltest', host: 'oel6idb', function: '开发'},
      {id: 9, sysname: 'dev', creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', role: '开发', email: 'dev@enmotech.com',
        dbname: 'ddltest', host: 'oel6idb', function: '开发'},
      {id: 10, sysname: 'dev', creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', role: '开发', email: 'dev@enmotech.com',
        dbname: 'ddltest', host: 'oel6idb', function: '开发'},
      {id: 11, sysname: 'dev', creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', role: '开发', email: 'dev@enmotech.com',
        dbname: 'ddltest', host: 'oel6idb', function: '开发'},
      {id: 12, sysname: 'dev', creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', role: '开发', email: 'dev@enmotech.com',
        dbname: 'ddltest', host: 'oel6idb', function: '开发'},
      {id: 13, sysname: 'dev', creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', role: '开发', email: 'dev@enmotech.com',
        dbname: 'ddltest', host: 'oel6idb', function: '开发'},
    ];
    const users = [
      {id: 0, name: 'ddd',  role: '开发', email: 'dev@enmotech.com'},
      {id: 1, name: 'dba', role: '开发', email: 'dev@enmotech.com'
       },
      {id: 2, name: 'abc', role: '开发', email: 'dev@enmotech.com'
       },
      {id: 3, name: 'eee', role: '开发', email: 'dev@enmotech.com'
       },
      {id: 4, name: '333',  role: '开发', email: 'dev@enmotech.com'
        },
      {id: 5, name: '222',  role: '开发', email: 'dev@enmotech.com'
        },
      {id: 6, name: 'dev',  role: '开发', email: 'dev@enmotech.com'
        },
      {id: 7, name: 'dev', role: '开发', email: 'dev@enmotech.com'
        },
      {id: 8, name: 'dev', role: '开发', email: 'dev@enmotech.com'
        },
      {id: 9, name: 'dev', role: '开发', email: 'dev@enmotech.com'
       },
      {id: 10, name: 'dev', role: '开发', email: 'dev@enmotech.com'
        },
      {id: 11, name: 'dev',  role: '开发', email: 'dev@enmotech.com'
       },
      {id: 12, name: 'dev',  role: '开发', email: 'dev@enmotech.com'
        },
      {id: 13, name: 'dev',  role: '开发', email: 'dev@enmotech.com'
        },
    ];
    const modules = [
      {id: 33, sysname: 'DDLAUDIT2', modulename: 'dev',principal: 'dev', comments: '--' },
      {id: 11, sysname: 'DDLAUDIT2', modulename: 'dev',principal: 'dev', comments: '--' },
      {id: 45, sysname: 'DDLAUDIT2', modulename: 'dev',principal: 'dev', comments: '--' },
      {id: 22, sysname: 'DDLAUDIT2', modulename: 'dev',principal: 'dev', comments: '--' },
      {id: 23, sysname: 'DDLAUDIT2', modulename: 'dev',principal: 'dev', comments: '--' },
      {id: 34, sysname: 'DDLAUDIT2', modulename: 'dev',principal: 'dev', comments: '--' },
      {id: 35, sysname: 'DDLAUDIT2', modulename: 'dev',principal: 'dev', comments: '--' },
      {id: 36, sysname: 'DDLAUDIT2', modulename: 'dev',principal: 'dev', comments: '--' },
      {id: 37, sysname: 'DDLAUDIT2', modulename: 'dev',principal: 'dev', comments: '--' },
      {id: 25, sysname: 'DDLAUDIT2', modulename: 'dev',principal: 'dev', comments: '--' },
      {id: 26, sysname: 'DDLAUDIT2', modulename: 'dev',principal: 'dev', comments: '--' },
      {id: 56, sysname: 'DDLAUDIT2', modulename: 'dev',principal: 'dev', comments: '--' },
      {id: 59, sysname: 'DDLAUDIT2', modulename: 'dev',principal: 'dev', comments: '--' },
      {id: 1, sysname: 'DDLAUDIT2', modulename: 'dev',principal: 'dev', comments: '--' },
      {id: 21, sysname: 'DDLAUDIT2', modulename: 'dev',principal: 'dev', comments: '--' },
      {id: 78, sysname: 'DDLAUDIT2', modulename: 'dev',principal: 'dev', comments: '--' },
    ];
    const schematables = [
      {id: 33, dbname: 'DDLAUDIT2', schema: 'ZONE',psdstate: '正常', function:'开发', comments: '--', tablename: 'Test' },
      {id: 11, dbname: 'DDLAUDIT2', schema: 'Z3',psdstate: '正常',  function:'开发', comments: '--' , tablename:'Test' },
      {id: 45, dbname: 'DDLAUDIT2', schema: 'ZONE',psdstate: '正常',function:'开发', comments: '--' , tablename:'Test' },
      {id: 22, dbname: 'DDLAUDIT2', schema: 'ZONE',psdstate: '正常', function:'开发',comments: '--' , tablename:'Test' },
      {id: 23, dbname: 'DDLAUDIT2', schema: 'Z3',psdstate: '正常', function:'开发',comments: '--' , tablename:'Test' },
      {id: 34, dbname: 'DDLAUDIT2', schema: 'Z3',psdstate: '正常', function:'开发',comments: '--' , tablename:'Test' },
      {id: 35, dbname: 'DDLAUDIT2', schema: 'Z3',psdstate: '正常', function:'开发', comments: '--' , tablename:'Test' },
      {id: 33, dbname: 'DDLAUDIT2', schema: 'ZONE',psdstate: '正常', function:'开发', comments: '--', tablename: 'Test' },
      {id: 11, dbname: 'DDLAUDIT2', schema: 'Z3',psdstate: '正常',  function:'开发', comments: '--' , tablename:'Test' },
      {id: 45, dbname: 'DDLAUDIT2', schema: 'ZONE',psdstate: '正常',function:'开发', comments: '--' , tablename:'Test' },
      {id: 22, dbname: 'DDLAUDIT2', schema: 'ZONE',psdstate: '正常', function:'开发',comments: '--' , tablename:'Test' },
      {id: 23, dbname: 'DDLAUDIT2', schema: 'Z3',psdstate: '正常', function:'开发',comments: '--' , tablename:'Test' },
      {id: 34, dbname: 'DDLAUDIT2', schema: 'Z3',psdstate: '正常', function:'开发',comments: '--' , tablename:'Test' },
      {id: 35, dbname: 'DDLAUDIT2', schema: 'Z3',psdstate: '正常', function:'开发', comments: '--' , tablename:'Test' },
      {id: 33, dbname: 'DDLAUDIT2', schema: 'ZONE',psdstate: '正常', function:'开发', comments: '--', tablename: 'Test' },
      {id: 11, dbname: 'DDLAUDIT2', schema: 'Z3',psdstate: '正常',  function:'开发', comments: '--' , tablename:'Test' },
      {id: 45, dbname: 'DDLAUDIT2', schema: 'ZONE',psdstate: '正常',function:'开发', comments: '--' , tablename:'Test' },
      {id: 22, dbname: 'DDLAUDIT2', schema: 'ZONE',psdstate: '正常', function:'开发',comments: '--' , tablename:'Test' },
      {id: 23, dbname: 'DDLAUDIT2', schema: 'Z3',psdstate: '正常', function:'开发',comments: '--' , tablename:'Test' },
      {id: 34, dbname: 'DDLAUDIT2', schema: 'Z3',psdstate: '正常', function:'开发',comments: '--' , tablename:'Test' },
      {id: 35, dbname: 'DDLAUDIT2', schema: 'Z3',psdstate: '正常', function:'开发', comments: '--' , tablename:'Test' }
    ];
    const projects = [
      {id: 10, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 12, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 14, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 15, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 16, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 21, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 23, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 26, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 29, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 33, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 45, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 44, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 46, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 31, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 7, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 52, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 42, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 54, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 71, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 77, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 92, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 37, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'},
      {id: 49, projectname:'zen项目迁移', sysname: 'dev', modulename:'ZONE',creatror: 'mydba', principal: 'dev', gmtCreate: '2016-12-30 10:38:14',
        gmtModified: '2016-12-30 10:38:14', comments: '--', state:'活动',members:'["pusheng","swl","zone_dev","angular"]'}

    ];
    const objects=[
      {id: 10, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 12, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 14, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 15, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 16, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 21, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 23, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 26, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 29, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 33, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 45, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 44, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 46, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 31, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 7, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 52, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 42, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 54, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 71, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 77, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 92, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 37, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'},
      {id: 49, objectType:'表', objectName: 'EMAIL_PROPRTIES', changeType:'变更',dataFunction: '配置数据', changePeople: 'dev',
        gmtModified: '2016-12-30 10:38:14', comments: '--'}

    ];
    const tables = [
      {id: 11, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 12, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 13, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 14, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 15, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 16, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 17, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 18, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 19, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 20, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 21, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 22, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 23, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 24, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 25, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 26, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 27, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 28, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 29, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 30, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 31, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 32, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 33, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'},
      {id: 34, tableName: 'COLLECT_DROUPS', lockState: '未锁', changePeople: 'zone_dev',   gmtModified: '2016-12-30 10:38:14',gmtCreate: '2016-12-30 10:38:14',
        comments: '主机监控项黑白名单关系备份表'}
    ];
    const sequences = [
      {id: 11, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--', step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 12, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 13, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 14, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 15, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 16, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 17, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 18, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 19, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 20, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 21, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 22, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 23, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 24, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 25, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 26, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 27, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 28, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 29, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 30, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 31, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 32, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 33, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'},
      {id: 34, sequenceName: 'SEQ_COLLECT', lockState: '未锁', minValue: '1',   maxValue: '--',step:'1', cache:'20', cicle:'N', order:'N',
        tableNumber:'7',gmtCreate: '2016-12-30 10:38:14', comments: 'SNAP_ID序列'}
    ];
    return {systems, users, modules, schematables, projects, objects, tables, sequences};
  }
}
